site_name: GitPub

nav:
  - Home: index.md
  - Contribuindo: contribuindo.md
  - Políticas:
    - Folha de Estilo: policies/folha-de-estilo.md 
    - Branches: policies/branches.md
    - Commits: policies/commits.md
    - Issue: policies/issues.md
    - Pull Request: policies/pull-request.md
  - Dinâmica 1:
    - Priorização Documentos: dinamica-1/priorizacao-documentos.md
    - Rich Picture: dinamica-1/richpicture.md
    - Argumentação: dinamica-1/argumentacao.md
    - Brainstorm: https://github.com/Desenho2018-2/GitPub/wiki/Brainstorm
    - Questionário: dinamica-1/questionario.md
    - Moscow: dinamica-1/moscow.md
    - Storytelling: dinamica-1/storytelling.md
    - Cenários: dinamica-1/cenarios.md
    - Lexicos: dinamica-1/lexicos.md
    - Protótipo Baixa Fidelidade: dinamica-1/prototipo-baixa-fidelidade.md
  - Dinâmica 2:
    - Metodologia: dinamica-2/metodologia.md
  - Dinâmica 3:
    - Product Backlog: dinamica-3/product-backlog.md
    - Diagrama de caso de uso: dinamica-3/diagrama-caso-de-uso.md
    - Diagrama de Classe: dinamica-3/diagrama-de-classe.md
    - Diagrama Sequencial: dinamica-3/diagrama-sequencial.md
    - iStar: dinamica-3/iStar.md
    - Strategic Dependency: dinamica-3/strategic-dependency.md
    - Strategic Rationale: dinamica-3/strategic-rationale.md
    - NFR Framework: dinamica-3/nfrFramework.md
    - Banco de Dados: dinamica-3/banco-de-dados.md
    - Protótipo Alta Fidelidade: /
  
theme:
  name: 'material'
  palette:
    primary: 'green'
    accent: 'blue'

markdown_extensions:
  - codehilite


