site_name: GitPub

nav:
  - Home: index.md
  - Contribuindo: contribuindo.md
  - Políticas:
    - Folha de Estilo: policies/folha-de-estilo.md 
    - Branches: policies/branches.md
    - Commits: policies/commits.md
    - Issue: policies/issues.md
    - Pull Request: policies/pull-request.md
  - Dinâmica 1:
    - Priorização Documentos: dinamica-1/priorizacao-documentos.md
    - Rich Picture: dinamica-1/richpicture.md
    - Argumentação: dinamica-1/argumentacao.md
    - Brainstorm: dinamica-1/brainstorm.md
    - Questionário: dinamica-1/questionario.md
    - Moscow: dinamica-1/moscow.md
    - Storytelling: dinamica-1/storytelling.md
    - Cenários: dinamica-1/cenarios.md
    - Lexicos: dinamica-1/lexicos.md
    - Protótipo Baixa Fidelidade: dinamica-1/prototipo-baixa-fidelidade.md
  - Dinâmica 2:
    - Metodologia: dinamica-2/metodologia.md
  - Dinâmica 3:
    - Product Backlog: dinamica-3/product-backlog.md
    - Diagrama de caso de uso: dinamica-3/diagrama-caso-de-uso.md
    - Diagrama de Classe: dinamica-3/diagrama-de-classe.md
    - Diagrama Sequencial: dinamica-3/diagrama-sequencial.md
    - iStar: dinamica-3/iStar.md
    - Strategic Dependency: dinamica-3/strategic-dependency.md
    - Strategic Rationale: dinamica-3/strategic-rationale.md
    - NFR Framework: dinamica-3/nfrFramework.md
    - Banco de Dados: dinamica-3/banco-de-dados.md
    - Protótipo Alta Fidelidade: /
  - Dinâmica 4:
    - Checklist: dinamica-4/checklist.md
    - Digrama de Pacotes: dinamica-4/diagrama-pacotes.md
    - Documento de Arquitetura: dinamica-4/documento-arquitetura.md
    - Matrizes de Rastreabilidade: dinamica-4/matrizes-de-rastreabilidade.md
    - Plano de Elicitação de Requisitos: dinamica-4/plano-elicitacao-requisitos.md
    - Pré-rastreabilidade: dinamica-4/pre-rastreabilidade.md
  - Padrões Aplicados:
    - Observer + decorator (Notifyr): padroes-aplicados/notifyr.md
    - Decorator (Log): padroes-aplicados/decorator.md
    - Singleton (Anonymous user): padroes-aplicados/singleton.md
    - Template method (Django): padroes-aplicados/template-method.md
    - Facade (Django): padroes-aplicados/facade.md
    - Class Table Inheritance (Arquitetural): padroes-aplicados/class-table-inheritance.md
  - Analise Metodologia de Desenvolvimento: reports/analise_metodologia_de_desenvolvimento.md
  
theme:
  name: 'material'
  palette:
    primary: 'green'
    accent: 'green'

markdown_extensions:
  - codehilite


